### ISSUE TITLE
terraform destroy failed

### ISSUE THREAD

**Issue by toabi** [gavinbunney/terraform-provider-kubectl#27]
`terraform destroy` failed with `Error: rpc error: code = Canceled desc = context canceled`

According to TRACE logging the fault lies in this provider. This might be the part:

```
2020/07/15 12:53:09 [TRACE] module.mongodb_service_broker: eval: *terraform.EvalWriteState
2020/07/15 12:53:09 [TRACE] EvalWriteState: recording 2 dependencies for module.mongodb_service_broker.kubectl_manifest.psmdb_operator
2020/07/15 12:53:09 [TRACE] EvalWriteState: writing current state object for module.mongodb_service_broker.kubectl_manifest.psmdb_operator
2020/07/15 12:53:09 [TRACE] [walkRefresh] Exiting eval tree: module.mongodb_service_broker.kubectl_manifest.psmdb_operator
2020/07/15 12:53:09 [TRACE] vertex "module.mongodb_service_broker.kubectl_manifest.psmdb_operator": visit complete
2020-07-15T12:53:10.024+0200 [DEBUG] plugin.terraform-provider-kubectl: 2020/07/15 12:53:10 [TRACE] Skipping as in SkipFields: map[string]interface {}{} map[string]interface {}{}
2020/07/15 12:53:10 [TRACE] module.mongodb_service_broker: eval: *terraform.EvalWriteState
2020/07/15 12:53:10 [TRACE] EvalWriteState: recording 2 dependencies for module.mongodb_service_broker.kubectl_manifest.psmdb_crds
2020/07/15 12:53:10 [TRACE] EvalWriteState: writing current state object for module.mongodb_service_broker.kubectl_manifest.psmdb_crds
2020/07/15 12:53:10 [TRACE] [walkRefresh] Exiting eval tree: module.mongodb_service_broker.kubectl_manifest.psmdb_crds
2020/07/15 12:53:10 [TRACE] vertex "module.mongodb_service_broker.kubectl_manifest.psmdb_crds": visit complete
2020-07-15T12:53:10.095+0200 [DEBUG] plugin.terraform-provider-kubectl: panic: interface conversion: interface {} is string, not map[string]interface {}
2020-07-15T12:53:10.095+0200 [DEBUG] plugin.terraform-provider-kubectl: 
2020-07-15T12:53:10.095+0200 [DEBUG] plugin.terraform-provider-kubectl: goroutine 39 [running]:
2020-07-15T12:53:10.095+0200 [DEBUG] plugin.terraform-provider-kubectl: github.com/gavinbunney/terraform-provider-kubectl/kubernetes.handleMaps(0x27179c0, 0xc0002baf90, 0x2674280, 0xc0007a0e20, 0x0, 0x0, 0x0, 0x2, 0x0, 0x0, ...)
2020-07-15T12:53:10.095+0200 [DEBUG] plugin.terraform-provider-kubectl: 	/home/travis/gopath/src/github.com/gavinbunney/terraform-provider-kubectl/kubernetes/diff_partial_compare.go:124 +0x432
2020-07-15T12:53:10.095+0200 [DEBUG] plugin.terraform-provider-kubectl: github.com/gavinbunney/terraform-provider-kubectl/kubernetes.getReturnedValueForOriginalFields(0xc0002baf60, 0xc0007a7dd0, 0x0, 0x0, 0x0, 0x2, 0x70000c0006b7e08, 0xffffffffffffffff, 0x0, 0xc0006a8d60)
2020-07-15T12:53:10.095+0200 [DEBUG] plugin.terraform-provider-kubectl: 	/home/travis/gopath/src/github.com/gavinbunney/terraform-provider-kubectl/kubernetes/diff_partial_compare.go:64 +0x269
2020-07-15T12:53:10.095+0200 [DEBUG] plugin.terraform-provider-kubectl: github.com/gavinbunney/terraform-provider-kubectl/kubernetes.handleMaps(0x27179c0, 0xc0002baf60, 0x27179c0, 0xc0007a7dd0, 0x0, 0x0, 0x0, 0xc000d22380, 0x3b, 0x2, ...)
2020-07-15T12:53:10.095+0200 [DEBUG] plugin.terraform-provider-kubectl: 	/home/travis/gopath/src/github.com/gavinbunney/terraform-provider-kubectl/kubernetes/diff_partial_compare.go:124 +0x9d
2020-07-15T12:53:10.095+0200 [DEBUG] plugin.terraform-provider-kubectl: github.com/gavinbunney/terraform-provider-kubectl/kubernetes.getReturnedValueForOriginalFields(0xc0002baf30, 0xc0007a7da0, 0x0, 0x0, 0x0, 0x3e00880, 0x10000c0006b8120, 0xffffffffffffffff, 0x0, 0xc0006a90a0)
2020-07-15T12:53:10.095+0200 [DEBUG] plugin.terraform-provider-kubectl: 	/home/travis/gopath/src/github.com/gavinbunney/terraform-provider-kubectl/kubernetes/diff_partial_compare.go:64 +0x269
2020-07-15T12:53:10.095+0200 [DEBUG] plugin.terraform-provider-kubectl: github.com/gavinbunney/terraform-provider-kubectl/kubernetes.handleMaps(0x27179c0, 0xc0002baf30, 0x27179c0, 0xc0007a7da0, 0x0, 0x0, 0x0, 0xc0004cd5cb, 0x1, 0x0, ...)
2020-07-15T12:53:10.095+0200 [DEBUG] plugin.terraform-provider-kubectl: 	/home/travis/gopath/src/github.com/gavinbunney/terraform-provider-kubectl/kubernetes/diff_partial_compare.go:124 +0x9d
2020-07-15T12:53:10.095+0200 [DEBUG] plugin.terraform-provider-kubectl: github.com/gavinbunney/terraform-provider-kubectl/kubernetes.getReturnedValueForOriginalFields(0xc0002baf00, 0xc0007a7d70, 0x0, 0x0, 0x0, 0x3e00880, 0x101283e, 0x29931ea, 0xc00036cef0, 0xa)
2020-07-15T12:53:10.095+0200 [DEBUG] plugin.terraform-provider-kubectl: 	/home/travis/gopath/src/github.com/gavinbunney/terraform-provider-kubectl/kubernetes/diff_partial_compare.go:64 +0x269
2020-07-15T12:53:10.095+0200 [DEBUG] plugin.terraform-provider-kubectl: github.com/gavinbunney/terraform-provider-kubectl/kubernetes.handleMaps(0x27179c0, 0xc0002baf00, 0x27179c0, 0xc0007a7d70, 0x0, 0x0, 0x0, 0x1, 0x0, 0x0, ...)
2020-07-15T12:53:10.095+0200 [DEBUG] plugin.terraform-provider-kubectl: 	/home/travis/gopath/src/github.com/gavinbunney/terraform-provider-kubectl/kubernetes/diff_partial_compare.go:124 +0x9d
2020-07-15T12:53:10.095+0200 [DEBUG] plugin.terraform-provider-kubectl: github.com/gavinbunney/terraform-provider-kubectl/kubernetes.getReturnedValueForOriginalFields(0xc0002bade0, 0xc0007a7c50, 0x0, 0x0, 0x0, 0x3e00880, 0x30000c0006b8750, 0xffffffffffffffff, 0x1, 0xc0003096d0)
2020-07-15T12:53:10.095+0200 [DEBUG] plugin.terraform-provider-kubectl: 	/home/travis/gopath/src/github.com/gavinbunney/terraform-provider-kubectl/kubernetes/diff_partial_compare.go:64 +0x269
2020-07-15T12:53:10.095+0200 [DEBUG] plugin.terraform-provider-kubectl: github.com/gavinbunney/terraform-provider-kubectl/kubernetes.handleMaps(0x27179c0, 0xc0002bade0, 0x27179c0, 0xc0007a7c50, 0x0, 0x0, 0x0, 0x3e4cc90, 0x0, 0x0, ...)
2020-07-15T12:53:10.095+0200 [DEBUG] plugin.terraform-provider-kubectl: 	/home/travis/gopath/src/github.com/gavinbunney/terraform-provider-kubectl/kubernetes/diff_partial_compare.go:124 +0x9d
2020-07-15T12:53:10.095+0200 [DEBUG] plugin.terraform-provider-kubectl: github.com/gavinbunney/terraform-provider-kubectl/kubernetes.getReturnedValueForOriginalFields(0xc0002ba900, 0xc0007a7b60, 0x0, 0x0, 0x0, 0x2, 0xc0006b8a68, 0xffffffffffffffff, 0x0, 0xc0002c0a60)
2020-07-15T12:53:10.095+0200 [DEBUG] plugin.terraform-provider-kubectl: 	/home/travis/gopath/src/github.com/gavinbunney/terraform-provider-kubectl/kubernetes/diff_partial_compare.go:93 +0x613
2020-07-15T12:53:10.096+0200 [DEBUG] plugin.terraform-provider-kubectl: github.com/gavinbunney/terraform-provider-kubectl/kubernetes.handleMaps(0x27179c0, 0xc0002ba900, 0x27179c0, 0xc0007a7b60, 0x0, 0x0, 0x0, 0x2, 0x2, 0x2, ...)
2020-07-15T12:53:10.096+0200 [DEBUG] plugin.terraform-provider-kubectl: 	/home/travis/gopath/src/github.com/gavinbunney/terraform-provider-kubectl/kubernetes/diff_partial_compare.go:124 +0x9d
2020-07-15T12:53:10.096+0200 [DEBUG] plugin.terraform-provider-kubectl: github.com/gavinbunney/terraform-provider-kubectl/kubernetes.getReturnedValueForOriginalFields(0xc0002ba570, 0xc0007a7ad0, 0x0, 0x0, 0x0, 0x3e00880, 0x40000c0006b8d80, 0xffffffffffffffff, 0x0, 0x3e4cc90)
2020-07-15T12:53:10.096+0200 [DEBUG] plugin.terraform-provider-kubectl: 	/home/travis/gopath/src/github.com/gavinbunney/terraform-provider-kubectl/kubernetes/diff_partial_compare.go:64 +0x269
2020-07-15T12:53:10.096+0200 [DEBUG] plugin.terraform-provider-kubectl: github.com/gavinbunney/terraform-provider-kubectl/kubernetes.handleMaps(0x27179c0, 0xc0002ba570, 0x27179c0, 0xc0007a7ad0, 0x0, 0x0, 0x0, 0x1, 0x0, 0x0, ...)
2020-07-15T12:53:10.096+0200 [DEBUG] plugin.terraform-provider-kubectl: 	/home/travis/gopath/src/github.com/gavinbunney/terraform-provider-kubectl/kubernetes/diff_partial_compare.go:124 +0x9d
2020-07-15T12:53:10.096+0200 [DEBUG] plugin.terraform-provider-kubectl: github.com/gavinbunney/terraform-provider-kubectl/kubernetes.getReturnedValueForOriginalFields(0xc0002ba450, 0xc0007a7aa0, 0x0, 0x0, 0x0, 0x27, 0x40000c0006b9098, 0xffffffffffffffff, 0x0, 0xc000781540)
2020-07-15T12:53:10.096+0200 [DEBUG] plugin.terraform-provider-kubectl: 	/home/travis/gopath/src/github.com/gavinbunney/terraform-provider-kubectl/kubernetes/diff_partial_compare.go:64 +0x269
2020-07-15T12:53:10.096+0200 [DEBUG] plugin.terraform-provider-kubectl: github.com/gavinbunney/terraform-provider-kubectl/kubernetes.handleMaps(0x27179c0, 0xc0002ba450, 0x27179c0, 0xc0007a7aa0, 0x0, 0x0, 0x0, 0x3e4cc90, 0x0, 0x0, ...)
2020-07-15T12:53:10.096+0200 [DEBUG] plugin.terraform-provider-kubectl: 	/home/travis/gopath/src/github.com/gavinbunney/terraform-provider-kubectl/kubernetes/diff_partial_compare.go:124 +0x9d
2020-07-15T12:53:10.096+0200 [DEBUG] plugin.terraform-provider-kubectl: github.com/gavinbunney/terraform-provider-kubectl/kubernetes.getReturnedValueForOriginalFields(0xc00032a990, 0xc0007a74a0, 0x0, 0x0, 0x0, 0x2, 0xc0006b93b0, 0xffffffffffffffff, 0x0, 0xc0002c07a0)
2020-07-15T12:53:10.096+0200 [DEBUG] plugin.terraform-provider-kubectl: 	/home/travis/gopath/src/github.com/gavinbunney/terraform-provider-kubectl/kubernetes/diff_partial_compare.go:93 +0x613
2020-07-15T12:53:10.096+0200 [DEBUG] plugin.terraform-provider-kubectl: github.com/gavinbunney/terraform-provider-kubectl/kubernetes.handleMaps(0x27179c0, 0xc00032a990, 0x27179c0, 0xc0007a74a0, 0x0, 0x0, 0x0, 0x2, 0x2, 0x2, ...)
2020-07-15T12:53:10.096+0200 [DEBUG] plugin.terraform-provider-kubectl: 	/home/travis/gopath/src/github.com/gavinbunney/terraform-provider-kubectl/kubernetes/diff_partial_compare.go:124 +0x9d
2020-07-15T12:53:10.096+0200 [DEBUG] plugin.terraform-provider-kubectl: github.com/gavinbunney/terraform-provider-kubectl/kubernetes.getReturnedValueForOriginalFields(0xc00032a330, 0xc0007a73e0, 0x0, 0x0, 0x0, 0xd, 0x2a6a908, 0x2634d80, 0xc000641ea0, 0x0)
2020-07-15T12:53:10.096+0200 [DEBUG] plugin.terraform-provider-kubectl: 	/home/travis/gopath/src/github.com/gavinbunney/terraform-provider-kubectl/kubernetes/diff_partial_compare.go:64 +0x269
2020-07-15T12:53:10.096+0200 [DEBUG] plugin.terraform-provider-kubectl: github.com/gavinbunney/terraform-provider-kubectl/kubernetes.compareMaps(0xc00032a330, 0xc0007a73e0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
2020-07-15T12:53:10.096+0200 [DEBUG] plugin.terraform-provider-kubectl: 	/home/travis/gopath/src/github.com/gavinbunney/terraform-provider-kubectl/kubernetes/diff_partial_compare.go:11 +0x74
2020-07-15T12:53:10.096+0200 [DEBUG] plugin.terraform-provider-kubectl: github.com/gavinbunney/terraform-provider-kubectl/kubernetes.resourceKubectlManifestReadUsingClient(0xc000478380, 0x2798880, 0xc0005d8600, 0x2e12da0, 0xc000369720, 0xc00036a2d8, 0x2918020, 0xc000478380)
2020-07-15T12:53:10.096+0200 [DEBUG] plugin.terraform-provider-kubectl: 	/home/travis/gopath/src/github.com/gavinbunney/terraform-provider-kubectl/kubernetes/resource_kubectl_manifest.go:489 +0x70b
2020-07-15T12:53:10.096+0200 [DEBUG] plugin.terraform-provider-kubectl: github.com/gavinbunney/terraform-provider-kubectl/kubernetes.resourceKubectlManifestRead(0xc000478380, 0x2798880, 0xc0005d8600, 0xc000478380, 0x0)
2020-07-15T12:53:10.096+0200 [DEBUG] plugin.terraform-provider-kubectl: 	/home/travis/gopath/src/github.com/gavinbunney/terraform-provider-kubectl/kubernetes/resource_kubectl_manifest.go:456 +0x1ea
2020-07-15T12:53:10.096+0200 [DEBUG] plugin.terraform-provider-kubectl: github.com/hashicorp/terraform/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc0004a5800, 0xc0009c65a0, 0x2798880, 0xc0005d8600, 0xc0009e0548, 0x0, 0x0)
2020-07-15T12:53:10.096+0200 [DEBUG] plugin.terraform-provider-kubectl: 	/home/travis/gopath/pkg/mod/github.com/hashicorp/terraform@v0.12.25/helper/schema/resource.go:455 +0x119
2020-07-15T12:53:10.096+0200 [DEBUG] plugin.terraform-provider-kubectl: github.com/hashicorp/terraform/helper/plugin.(*GRPCProviderServer).ReadResource(0xc00080a108, 0x2df9320, 0xc0009c5200, 0xc0009c64b0, 0xc00080a108, 0x0, 0xc000548a48)
2020-07-15T12:53:10.096+0200 [DEBUG] plugin.terraform-provider-kubectl: 	/home/travis/gopath/pkg/mod/github.com/hashicorp/terraform@v0.12.25/helper/plugin/grpc_provider.go:525 +0x3d8
2020-07-15T12:53:10.097+0200 [DEBUG] plugin.terraform-provider-kubectl: github.com/hashicorp/terraform/internal/tfplugin5._Provider_ReadResource_Handler(0x29026a0, 0xc00080a108, 0x2df9320, 0xc0009c5200, 0xc000134f60, 0x0, 0x2df9320, 0xc0009c5200, 0xc000a0a000, 0x5a7e)
2020-07-15T12:53:10.097+0200 [DEBUG] plugin.terraform-provider-kubectl: 	/home/travis/gopath/pkg/mod/github.com/hashicorp/terraform@v0.12.25/internal/tfplugin5/tfplugin5.pb.go:3153 +0x217
2020-07-15T12:53:10.097+0200 [DEBUG] plugin.terraform-provider-kubectl: google.golang.org/grpc.(*Server).processUnaryRPC(0xc000592420, 0x2e12c20, 0xc0006c2900, 0xc0009f8200, 0xc0004ce8a0, 0x3e08cd0, 0x0, 0x0, 0x0)
2020-07-15T12:53:10.097+0200 [DEBUG] plugin.terraform-provider-kubectl: 	/home/travis/gopath/pkg/mod/google.golang.org/grpc@v1.23.1/server.go:995 +0x460
2020-07-15T12:53:10.097+0200 [DEBUG] plugin.terraform-provider-kubectl: google.golang.org/grpc.(*Server).handleStream(0xc000592420, 0x2e12c20, 0xc0006c2900, 0xc0009f8200, 0x0)
2020-07-15T12:53:10.097+0200 [DEBUG] plugin.terraform-provider-kubectl: 	/home/travis/gopath/pkg/mod/google.golang.org/grpc@v1.23.1/server.go:1275 +0xd3d
2020-07-15T12:53:10.097+0200 [DEBUG] plugin.terraform-provider-kubectl: google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc0004d6230, 0xc000592420, 0x2e12c20, 0xc0006c2900, 0xc0009f8200)
2020-07-15T12:53:10.097+0200 [DEBUG] plugin.terraform-provider-kubectl: 	/home/travis/gopath/pkg/mod/google.golang.org/grpc@v1.23.1/server.go:710 +0xa1
2020-07-15T12:53:10.097+0200 [DEBUG] plugin.terraform-provider-kubectl: created by google.golang.org/grpc.(*Server).serveStreams.func1
2020-07-15T12:53:10.097+0200 [DEBUG] plugin.terraform-provider-kubectl: 	/home/travis/gopath/pkg/mod/google.golang.org/grpc@v1.23.1/server.go:708 +0xa1
2020-07-15T12:53:10.102+0200 [DEBUG] plugin: plugin process exited: path=/Users/toabi/.terraform.d/plugins/terraform-provider-kubectl pid=18974 error="exit status 2"
```

**Comment by gavinbunney** [comment]
Thanks @toabi - pushed a fix for this panic
